### ISSUE TITLE
[BLOCKER] Features for v4.4

### ISSUE THREAD

**Issue by minecrawler** [Skellods-Network/SHPS4Node#89]
v4.4 needs at least the following items to be fixed or implemented in its dependencies:

Bugs:

- [x] Will not use default vhost value for URL Skellods-Network/SHPS4Node-config#17
- [x] no CSS / JS on empty include table Skellods-Network/SHPS4Node-make#2

New Features:

- [x] Create config from template Skellods-Network/SHPS4Node-config#16
- [x] Create DB from templates Skellods-Network/SHPS4Node-SQL#7 and<br>
Skellods-Network/SHPS4Node-commandline#2
- [x] implement file upload Skellods-Network/SHPS4Node-file#2
- [x] Implement support for CSS-Layers with specificity Skellods-Network/SHPS4Node-CSS#2

Enhancements:

- [x] Implement Media Query Support Skellods-Network/SHPS4Node-CSS#3

**Comment by minecrawler** [comment]
Create config from template: **OK**
- Skellods-Network/SHPS4Node-config@b053ba71cc43deeb5c4b8db0f1407558d9a736f2
- Skellods-Network/SHPS4Node-commandline@9bf6b481ba43abc1faaf037a41ed48f5cab786ea

**Comment by minecrawler** [comment]
Create db from template: **OK**
- Skellods-Network/SHPS4Node-SQL@76fb0764698f1edd5da37278a333cf23e5f8fcef
- Skellods-Network/SHPS4Node-commandline@6bebfe3f764e332d51997b1a4af53a7f612ad929

**Comment by minecrawler** [comment]
File upload: **OK**
- Skellods-Network/SHPS4Node-file@ce091a298176be2170d074fae3100891ff257a0f
- Skellods-Network/SHPS4Node-sandbox@62e9f81d59d7076e7d6e259a4b57fd4f55eadbc5

**Comment by minecrawler** [comment]
CSS Layers: **OK**

- Skellods-Network/SHPS4Node-CSS@1fe4c82b7c67f1dfce1605f960c31ee60e15e398
- Skellods-Network/SHPS4Node@d05477f4e35987b8955eb5e35e15a98044247e8e

**Comment by minecrawler** [comment]
CSS mediaqueries: **OK**

- Skellods-Network/SHPS4Node-CSS@9235d67add9ba6ab0df592e52b5f47a43629d8ad

**Comment by minecrawler** [comment]
Now waiting for tests and releases of sub-modules.
